### ISSUE TITLE
About Us: Very Poor UI

### ISSUE THREAD

**Issue by wdzeng** [nycu-life/frontend#10]
![image](https://github.com/NYCU-ME/frontend/assets/39057640/44f6082f-08f3-43ed-8619-0213830a4613)

I can't imagine who can accept this UI design.

**Comment by LeeLin2602** [comment]
fix due to the misusing of dark mode

**Comment by LeeLin2602** [comment]
![image](https://github.com/NYCU-ME/frontend/assets/30391069/2b42f4a5-5b90-4920-bef2-7a94699dd66c)
