### ISSUE TITLE
DNS Management: Poor UI

### ISSUE THREAD

**Issue by wdzeng** [nycu-life/frontend#11]
![image](https://github.com/NYCU-ME/frontend/assets/39057640/113ee595-d84b-4b06-a3ac-b6f4d1c136cb)

Please carefully think of your theme.

**Comment by LeeLin2602** [comment]
fix due to the misusing of dark mode

**Comment by LeeLin2602** [comment]
![image](https://github.com/NYCU-ME/frontend/assets/30391069/5ce6c1b2-88b0-40a2-9fd8-a603a7a9a9ce)
