### ISSUE TITLE
Navbar: Poor UI

### ISSUE THREAD

**Issue by wdzeng** [nycu-life/frontend#7]
Mobile:

![Screenshot_20231219_200939_Brave](https://github.com/NYCU-ME/frontend/assets/39057640/15c3eaa3-81a8-4c61-9ffd-af7a2113ff92)

PC:

![image](https://github.com/NYCU-ME/frontend/assets/39057640/aff94357-9cb8-4103-95b4-d6ea172ab706)

行距很不好看

**Comment by LeeLin2602** [comment]
![image](https://github.com/NYCU-ME/frontend/assets/30391069/aa2bce93-89fd-4b26-9ab0-255a07136ff4)
![image](https://github.com/NYCU-ME/frontend/assets/30391069/8eedfc06-1e8e-4531-b2ec-78f3a295a274)
 更改行距，外加將 popup menu 弄成懸浮的。
